<?php

namespace EnumType;

use \WsdlToPhp\PackageBase\AbstractStructEnumBase;

/**
 * This class stands for externalSystemWithdrawalType EnumType
 * @subpackage Enumerations
 */
class ExternalSystemWithdrawalType extends AbstractStructEnumBase
{
    /**
     * Constant for value 'OK_PAY_ELECTRONIC_MONEY'
     * @return string 'OK_PAY_ELECTRONIC_MONEY'
     */
    const VALUE_OK_PAY_ELECTRONIC_MONEY = 'OK_PAY_ELECTRONIC_MONEY';
    /**
     * Constant for value 'PERFECT_MONEY_ELECTRONIC_MONEY'
     * @return string 'PERFECT_MONEY_ELECTRONIC_MONEY'
     */
    const VALUE_PERFECT_MONEY_ELECTRONIC_MONEY = 'PERFECT_MONEY_ELECTRONIC_MONEY';
    /**
     * Constant for value 'EGO_PAY_ELECTRONIC_MONEY'
     * @return string 'EGO_PAY_ELECTRONIC_MONEY'
     */
    const VALUE_EGO_PAY_ELECTRONIC_MONEY = 'EGO_PAY_ELECTRONIC_MONEY';
    /**
     * Constant for value 'PAXUM_ELECTRONIC_MONEY'
     * @return string 'PAXUM_ELECTRONIC_MONEY'
     */
    const VALUE_PAXUM_ELECTRONIC_MONEY = 'PAXUM_ELECTRONIC_MONEY';
    /**
     * Constant for value 'YANDEX_ELECTRONIC_MONEY'
     * @return string 'YANDEX_ELECTRONIC_MONEY'
     */
    const VALUE_YANDEX_ELECTRONIC_MONEY = 'YANDEX_ELECTRONIC_MONEY';
    /**
     * Constant for value 'PAYEER_ELECTRONIC_MONEY'
     * @return string 'PAYEER_ELECTRONIC_MONEY'
     */
    const VALUE_PAYEER_ELECTRONIC_MONEY = 'PAYEER_ELECTRONIC_MONEY';
    /**
     * Constant for value 'EXMO_BITCOIN_ELECTRONIC_MONEY'
     * @return string 'EXMO_BITCOIN_ELECTRONIC_MONEY'
     */
    const VALUE_EXMO_BITCOIN_ELECTRONIC_MONEY = 'EXMO_BITCOIN_ELECTRONIC_MONEY';
    /**
     * Constant for value 'COINBASE_ELECTRONIC_MONEY'
     * @return string 'COINBASE_ELECTRONIC_MONEY'
     */
    const VALUE_COINBASE_ELECTRONIC_MONEY = 'COINBASE_ELECTRONIC_MONEY';
    /**
     * Constant for value 'KITPS_PAYMENT_SYSTEM'
     * @return string 'KITPS_PAYMENT_SYSTEM'
     */
    const VALUE_KITPS_PAYMENT_SYSTEM = 'KITPS_PAYMENT_SYSTEM';
    /**
     * Constant for value 'TEST_PAYMENT_SYSTEM'
     * @return string 'TEST_PAYMENT_SYSTEM'
     */
    const VALUE_TEST_PAYMENT_SYSTEM = 'TEST_PAYMENT_SYSTEM';
    /**
     * Constant for value 'BTC_E_BITCOIN_ELECTRONIC_MONEY'
     * @return string 'BTC_E_BITCOIN_ELECTRONIC_MONEY'
     */
    const VALUE_BTC_E_BITCOIN_ELECTRONIC_MONEY = 'BTC_E_BITCOIN_ELECTRONIC_MONEY';
    /**
     * Constant for value 'NETEX_WEB_MONEY_ELECTRONIC_MONEY'
     * @return string 'NETEX_WEB_MONEY_ELECTRONIC_MONEY'
     */
    const VALUE_NETEX_WEB_MONEY_ELECTRONIC_MONEY = 'NETEX_WEB_MONEY_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BTC_E_ELECTRONIC_MONEY'
     * @return string 'BTC_E_ELECTRONIC_MONEY'
     */
    const VALUE_BTC_E_ELECTRONIC_MONEY = 'BTC_E_ELECTRONIC_MONEY';
    /**
     * Constant for value 'EXMO_ELECTRONIC_MONEY'
     * @return string 'EXMO_ELECTRONIC_MONEY'
     */
    const VALUE_EXMO_ELECTRONIC_MONEY = 'EXMO_ELECTRONIC_MONEY';
    /**
     * Constant for value 'ECOIN_ELECTRONIC_MONEY'
     * @return string 'ECOIN_ELECTRONIC_MONEY'
     */
    const VALUE_ECOIN_ELECTRONIC_MONEY = 'ECOIN_ELECTRONIC_MONEY';
    /**
     * Constant for value 'CAPITALIST_ELECTRONIC_MONEY'
     * @return string 'CAPITALIST_ELECTRONIC_MONEY'
     */
    const VALUE_CAPITALIST_ELECTRONIC_MONEY = 'CAPITALIST_ELECTRONIC_MONEY';
    /**
     * Constant for value 'MONETARU_RUSSIAN_BANK_CARD'
     * @return string 'MONETARU_RUSSIAN_BANK_CARD'
     */
    const VALUE_MONETARU_RUSSIAN_BANK_CARD = 'MONETARU_RUSSIAN_BANK_CARD';
    /**
     * Constant for value 'MONETARU_QIWI'
     * @return string 'MONETARU_QIWI'
     */
    const VALUE_MONETARU_QIWI = 'MONETARU_QIWI';
    /**
     * Constant for value 'INTERKASSA_UKRAINIAN_BANK_CARD'
     * @return string 'INTERKASSA_UKRAINIAN_BANK_CARD'
     */
    const VALUE_INTERKASSA_UKRAINIAN_BANK_CARD = 'INTERKASSA_UKRAINIAN_BANK_CARD';
    /**
     * Constant for value 'BITOK_ELECTRONIC_MONEY'
     * @return string 'BITOK_ELECTRONIC_MONEY'
     */
    const VALUE_BITOK_ELECTRONIC_MONEY = 'BITOK_ELECTRONIC_MONEY';
    /**
     * Constant for value 'PAYZA_ELECTRONIC_MONEY'
     * @return string 'PAYZA_ELECTRONIC_MONEY'
     */
    const VALUE_PAYZA_ELECTRONIC_MONEY = 'PAYZA_ELECTRONIC_MONEY';
    /**
     * Constant for value 'EPESE_ELECTRONIC_MONEY'
     * @return string 'EPESE_ELECTRONIC_MONEY'
     */
    const VALUE_EPESE_ELECTRONIC_MONEY = 'EPESE_ELECTRONIC_MONEY';
    /**
     * Constant for value 'PAYBOX_KZ_KAZAKHSTANI_BANK_CARD'
     * @return string 'PAYBOX_KZ_KAZAKHSTANI_BANK_CARD'
     */
    const VALUE_PAYBOX_KZ_KAZAKHSTANI_BANK_CARD = 'PAYBOX_KZ_KAZAKHSTANI_BANK_CARD';
    /**
     * Constant for value 'QIWI_ELECTRONIC_MONEY'
     * @return string 'QIWI_ELECTRONIC_MONEY'
     */
    const VALUE_QIWI_ELECTRONIC_MONEY = 'QIWI_ELECTRONIC_MONEY';
    /**
     * Constant for value 'QIWI_BANK_CARD'
     * @return string 'QIWI_BANK_CARD'
     */
    const VALUE_QIWI_BANK_CARD = 'QIWI_BANK_CARD';
    /**
     * Constant for value 'CREDIT_PILOT_RU_CARD'
     * @return string 'CREDIT_PILOT_RU_CARD'
     */
    const VALUE_CREDIT_PILOT_RU_CARD = 'CREDIT_PILOT_RU_CARD';
    /**
     * Constant for value 'CREDIT_PILOT_RU_BANK'
     * @return string 'CREDIT_PILOT_RU_BANK'
     */
    const VALUE_CREDIT_PILOT_RU_BANK = 'CREDIT_PILOT_RU_BANK';
    /**
     * Constant for value 'CREDIT_PILOT_WALLET_ONE'
     * @return string 'CREDIT_PILOT_WALLET_ONE'
     */
    const VALUE_CREDIT_PILOT_WALLET_ONE = 'CREDIT_PILOT_WALLET_ONE';
    /**
     * Constant for value 'CREDIT_PILOT_SERVICES_OTHER'
     * @return string 'CREDIT_PILOT_SERVICES_OTHER'
     */
    const VALUE_CREDIT_PILOT_SERVICES_OTHER = 'CREDIT_PILOT_SERVICES_OTHER';
    /**
     * Constant for value 'CREDIT_PILOT_SERVICES_BANK_PAYMENTS'
     * @return string 'CREDIT_PILOT_SERVICES_BANK_PAYMENTS'
     */
    const VALUE_CREDIT_PILOT_SERVICES_BANK_PAYMENTS = 'CREDIT_PILOT_SERVICES_BANK_PAYMENTS';
    /**
     * Constant for value 'CREDIT_PILOT_SERVICES_MOBILE_SERVICES'
     * @return string 'CREDIT_PILOT_SERVICES_MOBILE_SERVICES'
     */
    const VALUE_CREDIT_PILOT_SERVICES_MOBILE_SERVICES = 'CREDIT_PILOT_SERVICES_MOBILE_SERVICES';
    /**
     * Constant for value 'CREDIT_PILOT_SERVICES_TAXI'
     * @return string 'CREDIT_PILOT_SERVICES_TAXI'
     */
    const VALUE_CREDIT_PILOT_SERVICES_TAXI = 'CREDIT_PILOT_SERVICES_TAXI';
    /**
     * Constant for value 'CREDIT_PILOT_SERVICES_GAMES'
     * @return string 'CREDIT_PILOT_SERVICES_GAMES'
     */
    const VALUE_CREDIT_PILOT_SERVICES_GAMES = 'CREDIT_PILOT_SERVICES_GAMES';
    /**
     * Constant for value 'CREDIT_PILOT_SERVICES_INTERNET_TV_TELECOM'
     * @return string 'CREDIT_PILOT_SERVICES_INTERNET_TV_TELECOM'
     */
    const VALUE_CREDIT_PILOT_SERVICES_INTERNET_TV_TELECOM = 'CREDIT_PILOT_SERVICES_INTERNET_TV_TELECOM';
    /**
     * Constant for value 'CREDIT_PILOT_SERVICES_E_COMMERCE'
     * @return string 'CREDIT_PILOT_SERVICES_E_COMMERCE'
     */
    const VALUE_CREDIT_PILOT_SERVICES_E_COMMERCE = 'CREDIT_PILOT_SERVICES_E_COMMERCE';
    /**
     * Constant for value 'CREDIT_PILOT_SERVICES_UTILITY_BILLS'
     * @return string 'CREDIT_PILOT_SERVICES_UTILITY_BILLS'
     */
    const VALUE_CREDIT_PILOT_SERVICES_UTILITY_BILLS = 'CREDIT_PILOT_SERVICES_UTILITY_BILLS';
    /**
     * Constant for value 'CREDIT_PILOT_SERVICES_MICROFINANCE_ORGANIZATIONS'
     * @return string 'CREDIT_PILOT_SERVICES_MICROFINANCE_ORGANIZATIONS'
     */
    const VALUE_CREDIT_PILOT_SERVICES_MICROFINANCE_ORGANIZATIONS = 'CREDIT_PILOT_SERVICES_MICROFINANCE_ORGANIZATIONS';
    /**
     * Constant for value 'ADVCASH_VOUCHER'
     * @return string 'ADVCASH_VOUCHER'
     */
    const VALUE_ADVCASH_VOUCHER = 'ADVCASH_VOUCHER';
    /**
     * Constant for value 'WINPAY_BANK_CARD'
     * @return string 'WINPAY_BANK_CARD'
     */
    const VALUE_WINPAY_BANK_CARD = 'WINPAY_BANK_CARD';
    /**
     * Constant for value 'WINPAY_BANK_CARD_MONEYSWAP'
     * @return string 'WINPAY_BANK_CARD_MONEYSWAP'
     */
    const VALUE_WINPAY_BANK_CARD_MONEYSWAP = 'WINPAY_BANK_CARD_MONEYSWAP';
    /**
     * Constant for value 'WINPAY_BANK_CARD_ROLLING_RESERVE'
     * @return string 'WINPAY_BANK_CARD_ROLLING_RESERVE'
     */
    const VALUE_WINPAY_BANK_CARD_ROLLING_RESERVE = 'WINPAY_BANK_CARD_ROLLING_RESERVE';
    /**
     * Constant for value 'BIT_ONE_LOCAL_BANK_TRANSFER'
     * @return string 'BIT_ONE_LOCAL_BANK_TRANSFER'
     */
    const VALUE_BIT_ONE_LOCAL_BANK_TRANSFER = 'BIT_ONE_LOCAL_BANK_TRANSFER';
    /**
     * Constant for value 'BTC_E_ETHEREUM_ELECTRONIC_MONEY'
     * @return string 'BTC_E_ETHEREUM_ELECTRONIC_MONEY'
     */
    const VALUE_BTC_E_ETHEREUM_ELECTRONIC_MONEY = 'BTC_E_ETHEREUM_ELECTRONIC_MONEY';
    /**
     * Constant for value 'EPAY_ELECTRONIC_MONEY'
     * @return string 'EPAY_ELECTRONIC_MONEY'
     */
    const VALUE_EPAY_ELECTRONIC_MONEY = 'EPAY_ELECTRONIC_MONEY';
    /**
     * Constant for value 'YANDEX_CASSA_ELECTRONIC_MONEY'
     * @return string 'YANDEX_CASSA_ELECTRONIC_MONEY'
     */
    const VALUE_YANDEX_CASSA_ELECTRONIC_MONEY = 'YANDEX_CASSA_ELECTRONIC_MONEY';
    /**
     * Constant for value 'ECOIN_VOUCHER_ELECTRONIC_MONEY'
     * @return string 'ECOIN_VOUCHER_ELECTRONIC_MONEY'
     */
    const VALUE_ECOIN_VOUCHER_ELECTRONIC_MONEY = 'ECOIN_VOUCHER_ELECTRONIC_MONEY';
    /**
     * Constant for value 'PAYBOX_KZ_CASH_BY_CODE'
     * @return string 'PAYBOX_KZ_CASH_BY_CODE'
     */
    const VALUE_PAYBOX_KZ_CASH_BY_CODE = 'PAYBOX_KZ_CASH_BY_CODE';
    /**
     * Constant for value 'WEX_ELECTRONIC_MONEY'
     * @return string 'WEX_ELECTRONIC_MONEY'
     */
    const VALUE_WEX_ELECTRONIC_MONEY = 'WEX_ELECTRONIC_MONEY';
    /**
     * Constant for value 'WEX_BITCOIN_ELECTRONIC_MONEY'
     * @return string 'WEX_BITCOIN_ELECTRONIC_MONEY'
     */
    const VALUE_WEX_BITCOIN_ELECTRONIC_MONEY = 'WEX_BITCOIN_ELECTRONIC_MONEY';
    /**
     * Constant for value 'WEX_ETHEREUM_ELECTRONIC_MONEY'
     * @return string 'WEX_ETHEREUM_ELECTRONIC_MONEY'
     */
    const VALUE_WEX_ETHEREUM_ELECTRONIC_MONEY = 'WEX_ETHEREUM_ELECTRONIC_MONEY';
    /**
     * Constant for value 'WEX_BITCOIN_CASH_ELECTRONIC_MONEY'
     * @return string 'WEX_BITCOIN_CASH_ELECTRONIC_MONEY'
     */
    const VALUE_WEX_BITCOIN_CASH_ELECTRONIC_MONEY = 'WEX_BITCOIN_CASH_ELECTRONIC_MONEY';
    /**
     * Constant for value 'WINPAY_MOBILE'
     * @return string 'WINPAY_MOBILE'
     */
    const VALUE_WINPAY_MOBILE = 'WINPAY_MOBILE';
    /**
     * Constant for value 'WINPAY_QIWI'
     * @return string 'WINPAY_QIWI'
     */
    const VALUE_WINPAY_QIWI = 'WINPAY_QIWI';
    /**
     * Constant for value 'WINPAY_YANDEX'
     * @return string 'WINPAY_YANDEX'
     */
    const VALUE_WINPAY_YANDEX = 'WINPAY_YANDEX';
    /**
     * Constant for value 'FIO_SEPA'
     * @return string 'FIO_SEPA'
     */
    const VALUE_FIO_SEPA = 'FIO_SEPA';
    /**
     * Constant for value 'EXMO_ETHEREUM_ELECTRONIC_MONEY'
     * @return string 'EXMO_ETHEREUM_ELECTRONIC_MONEY'
     */
    const VALUE_EXMO_ETHEREUM_ELECTRONIC_MONEY = 'EXMO_ETHEREUM_ELECTRONIC_MONEY';
    /**
     * Constant for value 'EXMO_BITCOIN_CASH_ELECTRONIC_MONEY'
     * @return string 'EXMO_BITCOIN_CASH_ELECTRONIC_MONEY'
     */
    const VALUE_EXMO_BITCOIN_CASH_ELECTRONIC_MONEY = 'EXMO_BITCOIN_CASH_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BITFINEX_BITCOIN_ELECTRONIC_MONEY'
     * @return string 'BITFINEX_BITCOIN_ELECTRONIC_MONEY'
     */
    const VALUE_BITFINEX_BITCOIN_ELECTRONIC_MONEY = 'BITFINEX_BITCOIN_ELECTRONIC_MONEY';
    /**
     * Constant for value 'NORDPAY_SEPA'
     * @return string 'NORDPAY_SEPA'
     */
    const VALUE_NORDPAY_SEPA = 'NORDPAY_SEPA';
    /**
     * Constant for value 'MAJESTIC_SEPA'
     * @return string 'MAJESTIC_SEPA'
     */
    const VALUE_MAJESTIC_SEPA = 'MAJESTIC_SEPA';
    /**
     * Constant for value 'INTERKASSA_YANDEX'
     * @return string 'INTERKASSA_YANDEX'
     */
    const VALUE_INTERKASSA_YANDEX = 'INTERKASSA_YANDEX';
    /**
     * Constant for value 'BITFINEX_LITECOIN_ELECTRONIC_MONEY'
     * @return string 'BITFINEX_LITECOIN_ELECTRONIC_MONEY'
     */
    const VALUE_BITFINEX_LITECOIN_ELECTRONIC_MONEY = 'BITFINEX_LITECOIN_ELECTRONIC_MONEY';
    /**
     * Constant for value 'ASTROPAY_ARGENTINA_LOCAL_BANK_TRANSFER'
     * @return string 'ASTROPAY_ARGENTINA_LOCAL_BANK_TRANSFER'
     */
    const VALUE_ASTROPAY_ARGENTINA_LOCAL_BANK_TRANSFER = 'ASTROPAY_ARGENTINA_LOCAL_BANK_TRANSFER';
    /**
     * Constant for value 'ASTROPAY_CHILE_LOCAL_BANK_TRANSFER'
     * @return string 'ASTROPAY_CHILE_LOCAL_BANK_TRANSFER'
     */
    const VALUE_ASTROPAY_CHILE_LOCAL_BANK_TRANSFER = 'ASTROPAY_CHILE_LOCAL_BANK_TRANSFER';
    /**
     * Constant for value 'ASTROPAY_BRAZIL_LOCAL_BANK_TRANSFER'
     * @return string 'ASTROPAY_BRAZIL_LOCAL_BANK_TRANSFER'
     */
    const VALUE_ASTROPAY_BRAZIL_LOCAL_BANK_TRANSFER = 'ASTROPAY_BRAZIL_LOCAL_BANK_TRANSFER';
    /**
     * Constant for value 'ASTROPAY_COLOMBIA_LOCAL_BANK_TRANSFER'
     * @return string 'ASTROPAY_COLOMBIA_LOCAL_BANK_TRANSFER'
     */
    const VALUE_ASTROPAY_COLOMBIA_LOCAL_BANK_TRANSFER = 'ASTROPAY_COLOMBIA_LOCAL_BANK_TRANSFER';
    /**
     * Constant for value 'ASTROPAY_MEXICO_LOCAL_BANK_TRANSFER'
     * @return string 'ASTROPAY_MEXICO_LOCAL_BANK_TRANSFER'
     */
    const VALUE_ASTROPAY_MEXICO_LOCAL_BANK_TRANSFER = 'ASTROPAY_MEXICO_LOCAL_BANK_TRANSFER';
    /**
     * Constant for value 'ASTROPAY_PERU_LOCAL_BANK_TRANSFER'
     * @return string 'ASTROPAY_PERU_LOCAL_BANK_TRANSFER'
     */
    const VALUE_ASTROPAY_PERU_LOCAL_BANK_TRANSFER = 'ASTROPAY_PERU_LOCAL_BANK_TRANSFER';
    /**
     * Constant for value 'ASTROPAY_URUGUAY_LOCAL_BANK_TRANSFER'
     * @return string 'ASTROPAY_URUGUAY_LOCAL_BANK_TRANSFER'
     */
    const VALUE_ASTROPAY_URUGUAY_LOCAL_BANK_TRANSFER = 'ASTROPAY_URUGUAY_LOCAL_BANK_TRANSFER';
    /**
     * Constant for value 'ASTROPAY_CHINA_LOCAL_BANK_TRANSFER'
     * @return string 'ASTROPAY_CHINA_LOCAL_BANK_TRANSFER'
     */
    const VALUE_ASTROPAY_CHINA_LOCAL_BANK_TRANSFER = 'ASTROPAY_CHINA_LOCAL_BANK_TRANSFER';
    /**
     * Constant for value 'CREDIT_PILOT_YANDEX'
     * @return string 'CREDIT_PILOT_YANDEX'
     */
    const VALUE_CREDIT_PILOT_YANDEX = 'CREDIT_PILOT_YANDEX';
    /**
     * Constant for value 'NORDPAY_SWIFT'
     * @return string 'NORDPAY_SWIFT'
     */
    const VALUE_NORDPAY_SWIFT = 'NORDPAY_SWIFT';
    /**
     * Constant for value 'BITFINEX_BITCOIN_CASH_ELECTRONIC_MONEY'
     * @return string 'BITFINEX_BITCOIN_CASH_ELECTRONIC_MONEY'
     */
    const VALUE_BITFINEX_BITCOIN_CASH_ELECTRONIC_MONEY = 'BITFINEX_BITCOIN_CASH_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BITFINEX_RIPPLE_ELECTRONIC_MONEY'
     * @return string 'BITFINEX_RIPPLE_ELECTRONIC_MONEY'
     */
    const VALUE_BITFINEX_RIPPLE_ELECTRONIC_MONEY = 'BITFINEX_RIPPLE_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BITFINEX_ETHEREUM_ELECTRONIC_MONEY'
     * @return string 'BITFINEX_ETHEREUM_ELECTRONIC_MONEY'
     */
    const VALUE_BITFINEX_ETHEREUM_ELECTRONIC_MONEY = 'BITFINEX_ETHEREUM_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BITFINEX_ZCASH_ELECTRONIC_MONEY'
     * @return string 'BITFINEX_ZCASH_ELECTRONIC_MONEY'
     */
    const VALUE_BITFINEX_ZCASH_ELECTRONIC_MONEY = 'BITFINEX_ZCASH_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BITFINEX_TRON_ELECTRONIC_MONEY'
     * @return string 'BITFINEX_TRON_ELECTRONIC_MONEY'
     */
    const VALUE_BITFINEX_TRON_ELECTRONIC_MONEY = 'BITFINEX_TRON_ELECTRONIC_MONEY';
    /**
     * Constant for value 'OKLINK_INDONESIA_LOCAL_BANK_TRANSFER'
     * @return string 'OKLINK_INDONESIA_LOCAL_BANK_TRANSFER'
     */
    const VALUE_OKLINK_INDONESIA_LOCAL_BANK_TRANSFER = 'OKLINK_INDONESIA_LOCAL_BANK_TRANSFER';
    /**
     * Constant for value 'OKLINK_PHILIPPINES_LOCAL_BANK_TRANSFER'
     * @return string 'OKLINK_PHILIPPINES_LOCAL_BANK_TRANSFER'
     */
    const VALUE_OKLINK_PHILIPPINES_LOCAL_BANK_TRANSFER = 'OKLINK_PHILIPPINES_LOCAL_BANK_TRANSFER';
    /**
     * Constant for value 'OKLINK_THAILAND_LOCAL_BANK_TRANSFER'
     * @return string 'OKLINK_THAILAND_LOCAL_BANK_TRANSFER'
     */
    const VALUE_OKLINK_THAILAND_LOCAL_BANK_TRANSFER = 'OKLINK_THAILAND_LOCAL_BANK_TRANSFER';
    /**
     * Constant for value 'OKLINK_VIETNAM_LOCAL_BANK_TRANSFER'
     * @return string 'OKLINK_VIETNAM_LOCAL_BANK_TRANSFER'
     */
    const VALUE_OKLINK_VIETNAM_LOCAL_BANK_TRANSFER = 'OKLINK_VIETNAM_LOCAL_BANK_TRANSFER';
    /**
     * Constant for value 'OKLINK_AUSTRALIA_LOCAL_BANK_TRANSFER'
     * @return string 'OKLINK_AUSTRALIA_LOCAL_BANK_TRANSFER'
     */
    const VALUE_OKLINK_AUSTRALIA_LOCAL_BANK_TRANSFER = 'OKLINK_AUSTRALIA_LOCAL_BANK_TRANSFER';
    /**
     * Constant for value 'OKLINK_MALAYSIA_LOCAL_BANK_TRANSFER'
     * @return string 'OKLINK_MALAYSIA_LOCAL_BANK_TRANSFER'
     */
    const VALUE_OKLINK_MALAYSIA_LOCAL_BANK_TRANSFER = 'OKLINK_MALAYSIA_LOCAL_BANK_TRANSFER';
    /**
     * Constant for value 'RBK_BANK_CARD'
     * @return string 'RBK_BANK_CARD'
     */
    const VALUE_RBK_BANK_CARD = 'RBK_BANK_CARD';
    /**
     * Constant for value 'RBK_BANK_CARD_CRYPTO_NETTING'
     * @return string 'RBK_BANK_CARD_CRYPTO_NETTING'
     */
    const VALUE_RBK_BANK_CARD_CRYPTO_NETTING = 'RBK_BANK_CARD_CRYPTO_NETTING';
    /**
     * Constant for value 'RBK_BANK_CARD_NEW'
     * @return string 'RBK_BANK_CARD_NEW'
     */
    const VALUE_RBK_BANK_CARD_NEW = 'RBK_BANK_CARD_NEW';
    /**
     * Constant for value 'APPEXMONEY_BANK_CARD'
     * @return string 'APPEXMONEY_BANK_CARD'
     */
    const VALUE_APPEXMONEY_BANK_CARD = 'APPEXMONEY_BANK_CARD';
    /**
     * Constant for value 'YANDEX_KASSA_BANK_CARD'
     * @return string 'YANDEX_KASSA_BANK_CARD'
     */
    const VALUE_YANDEX_KASSA_BANK_CARD = 'YANDEX_KASSA_BANK_CARD';
    /**
     * Constant for value 'NORDPAY_SWIFT_BUSINESS'
     * @return string 'NORDPAY_SWIFT_BUSINESS'
     */
    const VALUE_NORDPAY_SWIFT_BUSINESS = 'NORDPAY_SWIFT_BUSINESS';
    /**
     * Constant for value 'NORDPAY_SEPA_BUSINESS'
     * @return string 'NORDPAY_SEPA_BUSINESS'
     */
    const VALUE_NORDPAY_SEPA_BUSINESS = 'NORDPAY_SEPA_BUSINESS';
    /**
     * Constant for value 'MAJESTIC_SEPA_BUSINESS'
     * @return string 'MAJESTIC_SEPA_BUSINESS'
     */
    const VALUE_MAJESTIC_SEPA_BUSINESS = 'MAJESTIC_SEPA_BUSINESS';
    /**
     * Constant for value 'KRAKEN_BITCOIN_ELECTRONIC_MONEY'
     * @return string 'KRAKEN_BITCOIN_ELECTRONIC_MONEY'
     */
    const VALUE_KRAKEN_BITCOIN_ELECTRONIC_MONEY = 'KRAKEN_BITCOIN_ELECTRONIC_MONEY';
    /**
     * Constant for value 'KRAKEN_LITECOIN_ELECTRONIC_MONEY'
     * @return string 'KRAKEN_LITECOIN_ELECTRONIC_MONEY'
     */
    const VALUE_KRAKEN_LITECOIN_ELECTRONIC_MONEY = 'KRAKEN_LITECOIN_ELECTRONIC_MONEY';
    /**
     * Constant for value 'KRAKEN_BITCOIN_CASH_ELECTRONIC_MONEY'
     * @return string 'KRAKEN_BITCOIN_CASH_ELECTRONIC_MONEY'
     */
    const VALUE_KRAKEN_BITCOIN_CASH_ELECTRONIC_MONEY = 'KRAKEN_BITCOIN_CASH_ELECTRONIC_MONEY';
    /**
     * Constant for value 'KRAKEN_RIPPLE_ELECTRONIC_MONEY'
     * @return string 'KRAKEN_RIPPLE_ELECTRONIC_MONEY'
     */
    const VALUE_KRAKEN_RIPPLE_ELECTRONIC_MONEY = 'KRAKEN_RIPPLE_ELECTRONIC_MONEY';
    /**
     * Constant for value 'KRAKEN_ETHEREUM_ELECTRONIC_MONEY'
     * @return string 'KRAKEN_ETHEREUM_ELECTRONIC_MONEY'
     */
    const VALUE_KRAKEN_ETHEREUM_ELECTRONIC_MONEY = 'KRAKEN_ETHEREUM_ELECTRONIC_MONEY';
    /**
     * Constant for value 'KRAKEN_ZCASH_ELECTRONIC_MONEY'
     * @return string 'KRAKEN_ZCASH_ELECTRONIC_MONEY'
     */
    const VALUE_KRAKEN_ZCASH_ELECTRONIC_MONEY = 'KRAKEN_ZCASH_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BITSTAMP_BITCOIN_ELECTRONIC_MONEY'
     * @return string 'BITSTAMP_BITCOIN_ELECTRONIC_MONEY'
     */
    const VALUE_BITSTAMP_BITCOIN_ELECTRONIC_MONEY = 'BITSTAMP_BITCOIN_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BITSTAMP_LITECOIN_ELECTRONIC_MONEY'
     * @return string 'BITSTAMP_LITECOIN_ELECTRONIC_MONEY'
     */
    const VALUE_BITSTAMP_LITECOIN_ELECTRONIC_MONEY = 'BITSTAMP_LITECOIN_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BITSTAMP_BITCOIN_CASH_ELECTRONIC_MONEY'
     * @return string 'BITSTAMP_BITCOIN_CASH_ELECTRONIC_MONEY'
     */
    const VALUE_BITSTAMP_BITCOIN_CASH_ELECTRONIC_MONEY = 'BITSTAMP_BITCOIN_CASH_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BITSTAMP_RIPPLE_ELECTRONIC_MONEY'
     * @return string 'BITSTAMP_RIPPLE_ELECTRONIC_MONEY'
     */
    const VALUE_BITSTAMP_RIPPLE_ELECTRONIC_MONEY = 'BITSTAMP_RIPPLE_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BITSTAMP_ETHEREUM_ELECTRONIC_MONEY'
     * @return string 'BITSTAMP_ETHEREUM_ELECTRONIC_MONEY'
     */
    const VALUE_BITSTAMP_ETHEREUM_ELECTRONIC_MONEY = 'BITSTAMP_ETHEREUM_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BITSTAMP_GIBRALTAR_BITCOIN_ELECTRONIC_MONEY'
     * @return string 'BITSTAMP_GIBRALTAR_BITCOIN_ELECTRONIC_MONEY'
     */
    const VALUE_BITSTAMP_GIBRALTAR_BITCOIN_ELECTRONIC_MONEY = 'BITSTAMP_GIBRALTAR_BITCOIN_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BITSTAMP_NORDPAY_BITCOIN_ELECTRONIC_MONEY'
     * @return string 'BITSTAMP_NORDPAY_BITCOIN_ELECTRONIC_MONEY'
     */
    const VALUE_BITSTAMP_NORDPAY_BITCOIN_ELECTRONIC_MONEY = 'BITSTAMP_NORDPAY_BITCOIN_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BITSTAMP_NORDPAY_LITECOIN_ELECTRONIC_MONEY'
     * @return string 'BITSTAMP_NORDPAY_LITECOIN_ELECTRONIC_MONEY'
     */
    const VALUE_BITSTAMP_NORDPAY_LITECOIN_ELECTRONIC_MONEY = 'BITSTAMP_NORDPAY_LITECOIN_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BITSTAMP_NORDPAY_BITCOIN_CASH_ELECTRONIC_MONEY'
     * @return string 'BITSTAMP_NORDPAY_BITCOIN_CASH_ELECTRONIC_MONEY'
     */
    const VALUE_BITSTAMP_NORDPAY_BITCOIN_CASH_ELECTRONIC_MONEY = 'BITSTAMP_NORDPAY_BITCOIN_CASH_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BITSTAMP_NORDPAY_RIPPLE_ELECTRONIC_MONEY'
     * @return string 'BITSTAMP_NORDPAY_RIPPLE_ELECTRONIC_MONEY'
     */
    const VALUE_BITSTAMP_NORDPAY_RIPPLE_ELECTRONIC_MONEY = 'BITSTAMP_NORDPAY_RIPPLE_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BITSTAMP_NORDPAY_ETHEREUM_ELECTRONIC_MONEY'
     * @return string 'BITSTAMP_NORDPAY_ETHEREUM_ELECTRONIC_MONEY'
     */
    const VALUE_BITSTAMP_NORDPAY_ETHEREUM_ELECTRONIC_MONEY = 'BITSTAMP_NORDPAY_ETHEREUM_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BITTREX_BITCOIN_ELECTRONIC_MONEY'
     * @return string 'BITTREX_BITCOIN_ELECTRONIC_MONEY'
     */
    const VALUE_BITTREX_BITCOIN_ELECTRONIC_MONEY = 'BITTREX_BITCOIN_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BITTREX_LITECOIN_ELECTRONIC_MONEY'
     * @return string 'BITTREX_LITECOIN_ELECTRONIC_MONEY'
     */
    const VALUE_BITTREX_LITECOIN_ELECTRONIC_MONEY = 'BITTREX_LITECOIN_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BITTREX_BITCOIN_CASH_ELECTRONIC_MONEY'
     * @return string 'BITTREX_BITCOIN_CASH_ELECTRONIC_MONEY'
     */
    const VALUE_BITTREX_BITCOIN_CASH_ELECTRONIC_MONEY = 'BITTREX_BITCOIN_CASH_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BITTREX_RIPPLE_ELECTRONIC_MONEY'
     * @return string 'BITTREX_RIPPLE_ELECTRONIC_MONEY'
     */
    const VALUE_BITTREX_RIPPLE_ELECTRONIC_MONEY = 'BITTREX_RIPPLE_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BITTREX_ETHEREUM_ELECTRONIC_MONEY'
     * @return string 'BITTREX_ETHEREUM_ELECTRONIC_MONEY'
     */
    const VALUE_BITTREX_ETHEREUM_ELECTRONIC_MONEY = 'BITTREX_ETHEREUM_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BITTREX_ZCASH_ELECTRONIC_MONEY'
     * @return string 'BITTREX_ZCASH_ELECTRONIC_MONEY'
     */
    const VALUE_BITTREX_ZCASH_ELECTRONIC_MONEY = 'BITTREX_ZCASH_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BITTREX_TRON_ELECTRONIC_MONEY'
     * @return string 'BITTREX_TRON_ELECTRONIC_MONEY'
     */
    const VALUE_BITTREX_TRON_ELECTRONIC_MONEY = 'BITTREX_TRON_ELECTRONIC_MONEY';
    /**
     * Constant for value 'OKCOIN_BITCOIN_ELECTRONIC_MONEY'
     * @return string 'OKCOIN_BITCOIN_ELECTRONIC_MONEY'
     */
    const VALUE_OKCOIN_BITCOIN_ELECTRONIC_MONEY = 'OKCOIN_BITCOIN_ELECTRONIC_MONEY';
    /**
     * Constant for value 'OKCOIN_LITECOIN_ELECTRONIC_MONEY'
     * @return string 'OKCOIN_LITECOIN_ELECTRONIC_MONEY'
     */
    const VALUE_OKCOIN_LITECOIN_ELECTRONIC_MONEY = 'OKCOIN_LITECOIN_ELECTRONIC_MONEY';
    /**
     * Constant for value 'OKCOIN_BITCOIN_CASH_ELECTRONIC_MONEY'
     * @return string 'OKCOIN_BITCOIN_CASH_ELECTRONIC_MONEY'
     */
    const VALUE_OKCOIN_BITCOIN_CASH_ELECTRONIC_MONEY = 'OKCOIN_BITCOIN_CASH_ELECTRONIC_MONEY';
    /**
     * Constant for value 'OKCOIN_RIPPLE_ELECTRONIC_MONEY'
     * @return string 'OKCOIN_RIPPLE_ELECTRONIC_MONEY'
     */
    const VALUE_OKCOIN_RIPPLE_ELECTRONIC_MONEY = 'OKCOIN_RIPPLE_ELECTRONIC_MONEY';
    /**
     * Constant for value 'OKCOIN_ETHEREUM_ELECTRONIC_MONEY'
     * @return string 'OKCOIN_ETHEREUM_ELECTRONIC_MONEY'
     */
    const VALUE_OKCOIN_ETHEREUM_ELECTRONIC_MONEY = 'OKCOIN_ETHEREUM_ELECTRONIC_MONEY';
    /**
     * Constant for value 'OKCOIN_ZCASH_ELECTRONIC_MONEY'
     * @return string 'OKCOIN_ZCASH_ELECTRONIC_MONEY'
     */
    const VALUE_OKCOIN_ZCASH_ELECTRONIC_MONEY = 'OKCOIN_ZCASH_ELECTRONIC_MONEY';
    /**
     * Constant for value 'OKCOIN_TRON_ELECTRONIC_MONEY'
     * @return string 'OKCOIN_TRON_ELECTRONIC_MONEY'
     */
    const VALUE_OKCOIN_TRON_ELECTRONIC_MONEY = 'OKCOIN_TRON_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BINANCE_BITCOIN_ELECTRONIC_MONEY'
     * @return string 'BINANCE_BITCOIN_ELECTRONIC_MONEY'
     */
    const VALUE_BINANCE_BITCOIN_ELECTRONIC_MONEY = 'BINANCE_BITCOIN_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BINANCE_LITECOIN_ELECTRONIC_MONEY'
     * @return string 'BINANCE_LITECOIN_ELECTRONIC_MONEY'
     */
    const VALUE_BINANCE_LITECOIN_ELECTRONIC_MONEY = 'BINANCE_LITECOIN_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BINANCE_BITCOIN_CASH_ELECTRONIC_MONEY'
     * @return string 'BINANCE_BITCOIN_CASH_ELECTRONIC_MONEY'
     */
    const VALUE_BINANCE_BITCOIN_CASH_ELECTRONIC_MONEY = 'BINANCE_BITCOIN_CASH_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BINANCE_RIPPLE_ELECTRONIC_MONEY'
     * @return string 'BINANCE_RIPPLE_ELECTRONIC_MONEY'
     */
    const VALUE_BINANCE_RIPPLE_ELECTRONIC_MONEY = 'BINANCE_RIPPLE_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BINANCE_ETHEREUM_ELECTRONIC_MONEY'
     * @return string 'BINANCE_ETHEREUM_ELECTRONIC_MONEY'
     */
    const VALUE_BINANCE_ETHEREUM_ELECTRONIC_MONEY = 'BINANCE_ETHEREUM_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BINANCE_ZCASH_ELECTRONIC_MONEY'
     * @return string 'BINANCE_ZCASH_ELECTRONIC_MONEY'
     */
    const VALUE_BINANCE_ZCASH_ELECTRONIC_MONEY = 'BINANCE_ZCASH_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BINANCE_TRON_ELECTRONIC_MONEY'
     * @return string 'BINANCE_TRON_ELECTRONIC_MONEY'
     */
    const VALUE_BINANCE_TRON_ELECTRONIC_MONEY = 'BINANCE_TRON_ELECTRONIC_MONEY';
    /**
     * Constant for value 'WINPAY_BITCOIN_ELECTRONIC_MONEY'
     * @return string 'WINPAY_BITCOIN_ELECTRONIC_MONEY'
     */
    const VALUE_WINPAY_BITCOIN_ELECTRONIC_MONEY = 'WINPAY_BITCOIN_ELECTRONIC_MONEY';
    /**
     * Constant for value 'OKLINK_UAE_LOCAL_BANK_TRANSFER'
     * @return string 'OKLINK_UAE_LOCAL_BANK_TRANSFER'
     */
    const VALUE_OKLINK_UAE_LOCAL_BANK_TRANSFER = 'OKLINK_UAE_LOCAL_BANK_TRANSFER';
    /**
     * Constant for value 'OKLINK_CANADA_LOCAL_BANK_TRANSFER'
     * @return string 'OKLINK_CANADA_LOCAL_BANK_TRANSFER'
     */
    const VALUE_OKLINK_CANADA_LOCAL_BANK_TRANSFER = 'OKLINK_CANADA_LOCAL_BANK_TRANSFER';
    /**
     * Constant for value 'OKLINK_DOKU_ELECTRONIC_MONEY'
     * @return string 'OKLINK_DOKU_ELECTRONIC_MONEY'
     */
    const VALUE_OKLINK_DOKU_ELECTRONIC_MONEY = 'OKLINK_DOKU_ELECTRONIC_MONEY';
    /**
     * Constant for value 'OKLINK_VIMO_ELECTRONIC_MONEY'
     * @return string 'OKLINK_VIMO_ELECTRONIC_MONEY'
     */
    const VALUE_OKLINK_VIMO_ELECTRONIC_MONEY = 'OKLINK_VIMO_ELECTRONIC_MONEY';
    /**
     * Constant for value 'ROYAL_PAY_BANK_CARD'
     * @return string 'ROYAL_PAY_BANK_CARD'
     */
    const VALUE_ROYAL_PAY_BANK_CARD = 'ROYAL_PAY_BANK_CARD';
    /**
     * Constant for value 'ROYAL_PAY_ADV_PROJECT_BANK_CARD'
     * @return string 'ROYAL_PAY_ADV_PROJECT_BANK_CARD'
     */
    const VALUE_ROYAL_PAY_ADV_PROJECT_BANK_CARD = 'ROYAL_PAY_ADV_PROJECT_BANK_CARD';
    /**
     * Constant for value 'ROYAL_PAY_CIS_BANK_CARD'
     * @return string 'ROYAL_PAY_CIS_BANK_CARD'
     */
    const VALUE_ROYAL_PAY_CIS_BANK_CARD = 'ROYAL_PAY_CIS_BANK_CARD';
    /**
     * Constant for value 'GRATA_PAY_BANK_CARD'
     * @return string 'GRATA_PAY_BANK_CARD'
     */
    const VALUE_GRATA_PAY_BANK_CARD = 'GRATA_PAY_BANK_CARD';
    /**
     * Constant for value 'GATE_EXPRESS_BANK_CARD'
     * @return string 'GATE_EXPRESS_BANK_CARD'
     */
    const VALUE_GATE_EXPRESS_BANK_CARD = 'GATE_EXPRESS_BANK_CARD';
    /**
     * Constant for value 'PAYSOFT_BANK_CARD'
     * @return string 'PAYSOFT_BANK_CARD'
     */
    const VALUE_PAYSOFT_BANK_CARD = 'PAYSOFT_BANK_CARD';
    /**
     * Constant for value 'GPAY_BANK_CARD'
     * @return string 'GPAY_BANK_CARD'
     */
    const VALUE_GPAY_BANK_CARD = 'GPAY_BANK_CARD';
    /**
     * Constant for value 'BITFINEX_USDTETHER_ELECTRONIC_MONEY'
     * @return string 'BITFINEX_USDTETHER_ELECTRONIC_MONEY'
     */
    const VALUE_BITFINEX_USDTETHER_ELECTRONIC_MONEY = 'BITFINEX_USDTETHER_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BINANCE_USDTETHER_OMNI_ELECTRONIC_MONEY'
     * @return string 'BINANCE_USDTETHER_OMNI_ELECTRONIC_MONEY'
     */
    const VALUE_BINANCE_USDTETHER_OMNI_ELECTRONIC_MONEY = 'BINANCE_USDTETHER_OMNI_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BINANCE_USDTETHER_ERC20_ELECTRONIC_MONEY'
     * @return string 'BINANCE_USDTETHER_ERC20_ELECTRONIC_MONEY'
     */
    const VALUE_BINANCE_USDTETHER_ERC_20_ELECTRONIC_MONEY = 'BINANCE_USDTETHER_ERC20_ELECTRONIC_MONEY';
    /**
     * Constant for value 'BINANCE_USDTETHER_TRC20_ELECTRONIC_MONEY'
     * @return string 'BINANCE_USDTETHER_TRC20_ELECTRONIC_MONEY'
     */
    const VALUE_BINANCE_USDTETHER_TRC_20_ELECTRONIC_MONEY = 'BINANCE_USDTETHER_TRC20_ELECTRONIC_MONEY';
    /**
     * Constant for value 'OKCOIN_USDTETHER_ELECTRONIC_MONEY'
     * @return string 'OKCOIN_USDTETHER_ELECTRONIC_MONEY'
     */
    const VALUE_OKCOIN_USDTETHER_ELECTRONIC_MONEY = 'OKCOIN_USDTETHER_ELECTRONIC_MONEY';
    /**
     * Constant for value 'OKCOIN_USDTETHER_ERC20_ELECTRONIC_MONEY'
     * @return string 'OKCOIN_USDTETHER_ERC20_ELECTRONIC_MONEY'
     */
    const VALUE_OKCOIN_USDTETHER_ERC_20_ELECTRONIC_MONEY = 'OKCOIN_USDTETHER_ERC20_ELECTRONIC_MONEY';
    /**
     * Constant for value 'OKCOIN_USD_COIN_ELECTRONIC_MONEY'
     * @return string 'OKCOIN_USD_COIN_ELECTRONIC_MONEY'
     */
    const VALUE_OKCOIN_USD_COIN_ELECTRONIC_MONEY = 'OKCOIN_USD_COIN_ELECTRONIC_MONEY';
    /**
     * Constant for value 'OKCOIN_DAI_ELECTRONIC_MONEY'
     * @return string 'OKCOIN_DAI_ELECTRONIC_MONEY'
     */
    const VALUE_OKCOIN_DAI_ELECTRONIC_MONEY = 'OKCOIN_DAI_ELECTRONIC_MONEY';
    /**
     * Constant for value 'OKCOIN_PAXOS_STANDARD_ELECTRONIC_MONEY'
     * @return string 'OKCOIN_PAXOS_STANDARD_ELECTRONIC_MONEY'
     */
    const VALUE_OKCOIN_PAXOS_STANDARD_ELECTRONIC_MONEY = 'OKCOIN_PAXOS_STANDARD_ELECTRONIC_MONEY';
    /**
     * Constant for value 'OKCOIN_TRUE_USD_ELECTRONIC_MONEY'
     * @return string 'OKCOIN_TRUE_USD_ELECTRONIC_MONEY'
     */
    const VALUE_OKCOIN_TRUE_USD_ELECTRONIC_MONEY = 'OKCOIN_TRUE_USD_ELECTRONIC_MONEY';
    /**
     * Constant for value 'OKCOIN_USDK_ELECTRONIC_MONEY'
     * @return string 'OKCOIN_USDK_ELECTRONIC_MONEY'
     */
    const VALUE_OKCOIN_USDK_ELECTRONIC_MONEY = 'OKCOIN_USDK_ELECTRONIC_MONEY';
    /**
     * Constant for value 'OKCOIN_STASIS_EURO_ELECTRONIC_MONEY'
     * @return string 'OKCOIN_STASIS_EURO_ELECTRONIC_MONEY'
     */
    const VALUE_OKCOIN_STASIS_EURO_ELECTRONIC_MONEY = 'OKCOIN_STASIS_EURO_ELECTRONIC_MONEY';
    /**
     * Constant for value 'OKCOIN_USDTETHER_TRC20_ELECTRONIC_MONEY'
     * @return string 'OKCOIN_USDTETHER_TRC20_ELECTRONIC_MONEY'
     */
    const VALUE_OKCOIN_USDTETHER_TRC_20_ELECTRONIC_MONEY = 'OKCOIN_USDTETHER_TRC20_ELECTRONIC_MONEY';
    /**
     * Constant for value 'EXMO_USDTETHER_ELECTRONIC_MONEY'
     * @return string 'EXMO_USDTETHER_ELECTRONIC_MONEY'
     */
    const VALUE_EXMO_USDTETHER_ELECTRONIC_MONEY = 'EXMO_USDTETHER_ELECTRONIC_MONEY';
    /**
     * Constant for value 'TALKBANK_WITHDRAWAL_TO_BANK_CARD'
     * @return string 'TALKBANK_WITHDRAWAL_TO_BANK_CARD'
     */
    const VALUE_TALKBANK_WITHDRAWAL_TO_BANK_CARD = 'TALKBANK_WITHDRAWAL_TO_BANK_CARD';
    /**
     * Constant for value 'TALKBANK_WITHDRAWAL_TO_BANK_CARD_NEW'
     * @return string 'TALKBANK_WITHDRAWAL_TO_BANK_CARD_NEW'
     */
    const VALUE_TALKBANK_WITHDRAWAL_TO_BANK_CARD_NEW = 'TALKBANK_WITHDRAWAL_TO_BANK_CARD_NEW';
    /**
     * Constant for value 'BRZTOKEN_ELECTRONIC_MONEY'
     * @return string 'BRZTOKEN_ELECTRONIC_MONEY'
     */
    const VALUE_BRZTOKEN_ELECTRONIC_MONEY = 'BRZTOKEN_ELECTRONIC_MONEY';
    /**
     * Constant for value 'EPAY_PAYOUT_TO_BANK_ACCOUNT'
     * @return string 'EPAY_PAYOUT_TO_BANK_ACCOUNT'
     */
    const VALUE_EPAY_PAYOUT_TO_BANK_ACCOUNT = 'EPAY_PAYOUT_TO_BANK_ACCOUNT';
    /**
     * Constant for value 'EPAY_PAYOUT_THROUGH_CASH_AGENT'
     * @return string 'EPAY_PAYOUT_THROUGH_CASH_AGENT'
     */
    const VALUE_EPAY_PAYOUT_THROUGH_CASH_AGENT = 'EPAY_PAYOUT_THROUGH_CASH_AGENT';
    /**
     * Constant for value 'GPAY_BANK_ACCOUNT'
     * @return string 'GPAY_BANK_ACCOUNT'
     */
    const VALUE_GPAY_BANK_ACCOUNT = 'GPAY_BANK_ACCOUNT';
    /**
     * Return allowed values
     * @uses self::VALUE_OK_PAY_ELECTRONIC_MONEY
     * @uses self::VALUE_PERFECT_MONEY_ELECTRONIC_MONEY
     * @uses self::VALUE_EGO_PAY_ELECTRONIC_MONEY
     * @uses self::VALUE_PAXUM_ELECTRONIC_MONEY
     * @uses self::VALUE_YANDEX_ELECTRONIC_MONEY
     * @uses self::VALUE_PAYEER_ELECTRONIC_MONEY
     * @uses self::VALUE_EXMO_BITCOIN_ELECTRONIC_MONEY
     * @uses self::VALUE_COINBASE_ELECTRONIC_MONEY
     * @uses self::VALUE_KITPS_PAYMENT_SYSTEM
     * @uses self::VALUE_TEST_PAYMENT_SYSTEM
     * @uses self::VALUE_BTC_E_BITCOIN_ELECTRONIC_MONEY
     * @uses self::VALUE_NETEX_WEB_MONEY_ELECTRONIC_MONEY
     * @uses self::VALUE_BTC_E_ELECTRONIC_MONEY
     * @uses self::VALUE_EXMO_ELECTRONIC_MONEY
     * @uses self::VALUE_ECOIN_ELECTRONIC_MONEY
     * @uses self::VALUE_CAPITALIST_ELECTRONIC_MONEY
     * @uses self::VALUE_MONETARU_RUSSIAN_BANK_CARD
     * @uses self::VALUE_MONETARU_QIWI
     * @uses self::VALUE_INTERKASSA_UKRAINIAN_BANK_CARD
     * @uses self::VALUE_BITOK_ELECTRONIC_MONEY
     * @uses self::VALUE_PAYZA_ELECTRONIC_MONEY
     * @uses self::VALUE_EPESE_ELECTRONIC_MONEY
     * @uses self::VALUE_PAYBOX_KZ_KAZAKHSTANI_BANK_CARD
     * @uses self::VALUE_QIWI_ELECTRONIC_MONEY
     * @uses self::VALUE_QIWI_BANK_CARD
     * @uses self::VALUE_CREDIT_PILOT_RU_CARD
     * @uses self::VALUE_CREDIT_PILOT_RU_BANK
     * @uses self::VALUE_CREDIT_PILOT_WALLET_ONE
     * @uses self::VALUE_CREDIT_PILOT_SERVICES_OTHER
     * @uses self::VALUE_CREDIT_PILOT_SERVICES_BANK_PAYMENTS
     * @uses self::VALUE_CREDIT_PILOT_SERVICES_MOBILE_SERVICES
     * @uses self::VALUE_CREDIT_PILOT_SERVICES_TAXI
     * @uses self::VALUE_CREDIT_PILOT_SERVICES_GAMES
     * @uses self::VALUE_CREDIT_PILOT_SERVICES_INTERNET_TV_TELECOM
     * @uses self::VALUE_CREDIT_PILOT_SERVICES_E_COMMERCE
     * @uses self::VALUE_CREDIT_PILOT_SERVICES_UTILITY_BILLS
     * @uses self::VALUE_CREDIT_PILOT_SERVICES_MICROFINANCE_ORGANIZATIONS
     * @uses self::VALUE_ADVCASH_VOUCHER
     * @uses self::VALUE_WINPAY_BANK_CARD
     * @uses self::VALUE_WINPAY_BANK_CARD_MONEYSWAP
     * @uses self::VALUE_WINPAY_BANK_CARD_ROLLING_RESERVE
     * @uses self::VALUE_BIT_ONE_LOCAL_BANK_TRANSFER
     * @uses self::VALUE_BTC_E_ETHEREUM_ELECTRONIC_MONEY
     * @uses self::VALUE_EPAY_ELECTRONIC_MONEY
     * @uses self::VALUE_YANDEX_CASSA_ELECTRONIC_MONEY
     * @uses self::VALUE_ECOIN_VOUCHER_ELECTRONIC_MONEY
     * @uses self::VALUE_PAYBOX_KZ_CASH_BY_CODE
     * @uses self::VALUE_WEX_ELECTRONIC_MONEY
     * @uses self::VALUE_WEX_BITCOIN_ELECTRONIC_MONEY
     * @uses self::VALUE_WEX_ETHEREUM_ELECTRONIC_MONEY
     * @uses self::VALUE_WEX_BITCOIN_CASH_ELECTRONIC_MONEY
     * @uses self::VALUE_WINPAY_MOBILE
     * @uses self::VALUE_WINPAY_QIWI
     * @uses self::VALUE_WINPAY_YANDEX
     * @uses self::VALUE_FIO_SEPA
     * @uses self::VALUE_EXMO_ETHEREUM_ELECTRONIC_MONEY
     * @uses self::VALUE_EXMO_BITCOIN_CASH_ELECTRONIC_MONEY
     * @uses self::VALUE_BITFINEX_BITCOIN_ELECTRONIC_MONEY
     * @uses self::VALUE_NORDPAY_SEPA
     * @uses self::VALUE_MAJESTIC_SEPA
     * @uses self::VALUE_INTERKASSA_YANDEX
     * @uses self::VALUE_BITFINEX_LITECOIN_ELECTRONIC_MONEY
     * @uses self::VALUE_ASTROPAY_ARGENTINA_LOCAL_BANK_TRANSFER
     * @uses self::VALUE_ASTROPAY_CHILE_LOCAL_BANK_TRANSFER
     * @uses self::VALUE_ASTROPAY_BRAZIL_LOCAL_BANK_TRANSFER
     * @uses self::VALUE_ASTROPAY_COLOMBIA_LOCAL_BANK_TRANSFER
     * @uses self::VALUE_ASTROPAY_MEXICO_LOCAL_BANK_TRANSFER
     * @uses self::VALUE_ASTROPAY_PERU_LOCAL_BANK_TRANSFER
     * @uses self::VALUE_ASTROPAY_URUGUAY_LOCAL_BANK_TRANSFER
     * @uses self::VALUE_ASTROPAY_CHINA_LOCAL_BANK_TRANSFER
     * @uses self::VALUE_CREDIT_PILOT_YANDEX
     * @uses self::VALUE_NORDPAY_SWIFT
     * @uses self::VALUE_BITFINEX_BITCOIN_CASH_ELECTRONIC_MONEY
     * @uses self::VALUE_BITFINEX_RIPPLE_ELECTRONIC_MONEY
     * @uses self::VALUE_BITFINEX_ETHEREUM_ELECTRONIC_MONEY
     * @uses self::VALUE_BITFINEX_ZCASH_ELECTRONIC_MONEY
     * @uses self::VALUE_BITFINEX_TRON_ELECTRONIC_MONEY
     * @uses self::VALUE_OKLINK_INDONESIA_LOCAL_BANK_TRANSFER
     * @uses self::VALUE_OKLINK_PHILIPPINES_LOCAL_BANK_TRANSFER
     * @uses self::VALUE_OKLINK_THAILAND_LOCAL_BANK_TRANSFER
     * @uses self::VALUE_OKLINK_VIETNAM_LOCAL_BANK_TRANSFER
     * @uses self::VALUE_OKLINK_AUSTRALIA_LOCAL_BANK_TRANSFER
     * @uses self::VALUE_OKLINK_MALAYSIA_LOCAL_BANK_TRANSFER
     * @uses self::VALUE_RBK_BANK_CARD
     * @uses self::VALUE_RBK_BANK_CARD_CRYPTO_NETTING
     * @uses self::VALUE_RBK_BANK_CARD_NEW
     * @uses self::VALUE_APPEXMONEY_BANK_CARD
     * @uses self::VALUE_YANDEX_KASSA_BANK_CARD
     * @uses self::VALUE_NORDPAY_SWIFT_BUSINESS
     * @uses self::VALUE_NORDPAY_SEPA_BUSINESS
     * @uses self::VALUE_MAJESTIC_SEPA_BUSINESS
     * @uses self::VALUE_KRAKEN_BITCOIN_ELECTRONIC_MONEY
     * @uses self::VALUE_KRAKEN_LITECOIN_ELECTRONIC_MONEY
     * @uses self::VALUE_KRAKEN_BITCOIN_CASH_ELECTRONIC_MONEY
     * @uses self::VALUE_KRAKEN_RIPPLE_ELECTRONIC_MONEY
     * @uses self::VALUE_KRAKEN_ETHEREUM_ELECTRONIC_MONEY
     * @uses self::VALUE_KRAKEN_ZCASH_ELECTRONIC_MONEY
     * @uses self::VALUE_BITSTAMP_BITCOIN_ELECTRONIC_MONEY
     * @uses self::VALUE_BITSTAMP_LITECOIN_ELECTRONIC_MONEY
     * @uses self::VALUE_BITSTAMP_BITCOIN_CASH_ELECTRONIC_MONEY
     * @uses self::VALUE_BITSTAMP_RIPPLE_ELECTRONIC_MONEY
     * @uses self::VALUE_BITSTAMP_ETHEREUM_ELECTRONIC_MONEY
     * @uses self::VALUE_BITSTAMP_GIBRALTAR_BITCOIN_ELECTRONIC_MONEY
     * @uses self::VALUE_BITSTAMP_NORDPAY_BITCOIN_ELECTRONIC_MONEY
     * @uses self::VALUE_BITSTAMP_NORDPAY_LITECOIN_ELECTRONIC_MONEY
     * @uses self::VALUE_BITSTAMP_NORDPAY_BITCOIN_CASH_ELECTRONIC_MONEY
     * @uses self::VALUE_BITSTAMP_NORDPAY_RIPPLE_ELECTRONIC_MONEY
     * @uses self::VALUE_BITSTAMP_NORDPAY_ETHEREUM_ELECTRONIC_MONEY
     * @uses self::VALUE_BITTREX_BITCOIN_ELECTRONIC_MONEY
     * @uses self::VALUE_BITTREX_LITECOIN_ELECTRONIC_MONEY
     * @uses self::VALUE_BITTREX_BITCOIN_CASH_ELECTRONIC_MONEY
     * @uses self::VALUE_BITTREX_RIPPLE_ELECTRONIC_MONEY
     * @uses self::VALUE_BITTREX_ETHEREUM_ELECTRONIC_MONEY
     * @uses self::VALUE_BITTREX_ZCASH_ELECTRONIC_MONEY
     * @uses self::VALUE_BITTREX_TRON_ELECTRONIC_MONEY
     * @uses self::VALUE_OKCOIN_BITCOIN_ELECTRONIC_MONEY
     * @uses self::VALUE_OKCOIN_LITECOIN_ELECTRONIC_MONEY
     * @uses self::VALUE_OKCOIN_BITCOIN_CASH_ELECTRONIC_MONEY
     * @uses self::VALUE_OKCOIN_RIPPLE_ELECTRONIC_MONEY
     * @uses self::VALUE_OKCOIN_ETHEREUM_ELECTRONIC_MONEY
     * @uses self::VALUE_OKCOIN_ZCASH_ELECTRONIC_MONEY
     * @uses self::VALUE_OKCOIN_TRON_ELECTRONIC_MONEY
     * @uses self::VALUE_BINANCE_BITCOIN_ELECTRONIC_MONEY
     * @uses self::VALUE_BINANCE_LITECOIN_ELECTRONIC_MONEY
     * @uses self::VALUE_BINANCE_BITCOIN_CASH_ELECTRONIC_MONEY
     * @uses self::VALUE_BINANCE_RIPPLE_ELECTRONIC_MONEY
     * @uses self::VALUE_BINANCE_ETHEREUM_ELECTRONIC_MONEY
     * @uses self::VALUE_BINANCE_ZCASH_ELECTRONIC_MONEY
     * @uses self::VALUE_BINANCE_TRON_ELECTRONIC_MONEY
     * @uses self::VALUE_WINPAY_BITCOIN_ELECTRONIC_MONEY
     * @uses self::VALUE_OKLINK_UAE_LOCAL_BANK_TRANSFER
     * @uses self::VALUE_OKLINK_CANADA_LOCAL_BANK_TRANSFER
     * @uses self::VALUE_OKLINK_DOKU_ELECTRONIC_MONEY
     * @uses self::VALUE_OKLINK_VIMO_ELECTRONIC_MONEY
     * @uses self::VALUE_ROYAL_PAY_BANK_CARD
     * @uses self::VALUE_ROYAL_PAY_ADV_PROJECT_BANK_CARD
     * @uses self::VALUE_ROYAL_PAY_CIS_BANK_CARD
     * @uses self::VALUE_GRATA_PAY_BANK_CARD
     * @uses self::VALUE_GATE_EXPRESS_BANK_CARD
     * @uses self::VALUE_PAYSOFT_BANK_CARD
     * @uses self::VALUE_GPAY_BANK_CARD
     * @uses self::VALUE_BITFINEX_USDTETHER_ELECTRONIC_MONEY
     * @uses self::VALUE_BINANCE_USDTETHER_OMNI_ELECTRONIC_MONEY
     * @uses self::VALUE_BINANCE_USDTETHER_ERC_20_ELECTRONIC_MONEY
     * @uses self::VALUE_BINANCE_USDTETHER_TRC_20_ELECTRONIC_MONEY
     * @uses self::VALUE_OKCOIN_USDTETHER_ELECTRONIC_MONEY
     * @uses self::VALUE_OKCOIN_USDTETHER_ERC_20_ELECTRONIC_MONEY
     * @uses self::VALUE_OKCOIN_USD_COIN_ELECTRONIC_MONEY
     * @uses self::VALUE_OKCOIN_DAI_ELECTRONIC_MONEY
     * @uses self::VALUE_OKCOIN_PAXOS_STANDARD_ELECTRONIC_MONEY
     * @uses self::VALUE_OKCOIN_TRUE_USD_ELECTRONIC_MONEY
     * @uses self::VALUE_OKCOIN_USDK_ELECTRONIC_MONEY
     * @uses self::VALUE_OKCOIN_STASIS_EURO_ELECTRONIC_MONEY
     * @uses self::VALUE_OKCOIN_USDTETHER_TRC_20_ELECTRONIC_MONEY
     * @uses self::VALUE_EXMO_USDTETHER_ELECTRONIC_MONEY
     * @uses self::VALUE_TALKBANK_WITHDRAWAL_TO_BANK_CARD
     * @uses self::VALUE_TALKBANK_WITHDRAWAL_TO_BANK_CARD_NEW
     * @uses self::VALUE_BRZTOKEN_ELECTRONIC_MONEY
     * @uses self::VALUE_EPAY_PAYOUT_TO_BANK_ACCOUNT
     * @uses self::VALUE_EPAY_PAYOUT_THROUGH_CASH_AGENT
     * @uses self::VALUE_GPAY_BANK_ACCOUNT
     * @return string[]
     */
    public static function getValidValues()
    {
        return array(
            self::VALUE_OK_PAY_ELECTRONIC_MONEY,
            self::VALUE_PERFECT_MONEY_ELECTRONIC_MONEY,
            self::VALUE_EGO_PAY_ELECTRONIC_MONEY,
            self::VALUE_PAXUM_ELECTRONIC_MONEY,
            self::VALUE_YANDEX_ELECTRONIC_MONEY,
            self::VALUE_PAYEER_ELECTRONIC_MONEY,
            self::VALUE_EXMO_BITCOIN_ELECTRONIC_MONEY,
            self::VALUE_COINBASE_ELECTRONIC_MONEY,
            self::VALUE_KITPS_PAYMENT_SYSTEM,
            self::VALUE_TEST_PAYMENT_SYSTEM,
            self::VALUE_BTC_E_BITCOIN_ELECTRONIC_MONEY,
            self::VALUE_NETEX_WEB_MONEY_ELECTRONIC_MONEY,
            self::VALUE_BTC_E_ELECTRONIC_MONEY,
            self::VALUE_EXMO_ELECTRONIC_MONEY,
            self::VALUE_ECOIN_ELECTRONIC_MONEY,
            self::VALUE_CAPITALIST_ELECTRONIC_MONEY,
            self::VALUE_MONETARU_RUSSIAN_BANK_CARD,
            self::VALUE_MONETARU_QIWI,
            self::VALUE_INTERKASSA_UKRAINIAN_BANK_CARD,
            self::VALUE_BITOK_ELECTRONIC_MONEY,
            self::VALUE_PAYZA_ELECTRONIC_MONEY,
            self::VALUE_EPESE_ELECTRONIC_MONEY,
            self::VALUE_PAYBOX_KZ_KAZAKHSTANI_BANK_CARD,
            self::VALUE_QIWI_ELECTRONIC_MONEY,
            self::VALUE_QIWI_BANK_CARD,
            self::VALUE_CREDIT_PILOT_RU_CARD,
            self::VALUE_CREDIT_PILOT_RU_BANK,
            self::VALUE_CREDIT_PILOT_WALLET_ONE,
            self::VALUE_CREDIT_PILOT_SERVICES_OTHER,
            self::VALUE_CREDIT_PILOT_SERVICES_BANK_PAYMENTS,
            self::VALUE_CREDIT_PILOT_SERVICES_MOBILE_SERVICES,
            self::VALUE_CREDIT_PILOT_SERVICES_TAXI,
            self::VALUE_CREDIT_PILOT_SERVICES_GAMES,
            self::VALUE_CREDIT_PILOT_SERVICES_INTERNET_TV_TELECOM,
            self::VALUE_CREDIT_PILOT_SERVICES_E_COMMERCE,
            self::VALUE_CREDIT_PILOT_SERVICES_UTILITY_BILLS,
            self::VALUE_CREDIT_PILOT_SERVICES_MICROFINANCE_ORGANIZATIONS,
            self::VALUE_ADVCASH_VOUCHER,
            self::VALUE_WINPAY_BANK_CARD,
            self::VALUE_WINPAY_BANK_CARD_MONEYSWAP,
            self::VALUE_WINPAY_BANK_CARD_ROLLING_RESERVE,
            self::VALUE_BIT_ONE_LOCAL_BANK_TRANSFER,
            self::VALUE_BTC_E_ETHEREUM_ELECTRONIC_MONEY,
            self::VALUE_EPAY_ELECTRONIC_MONEY,
            self::VALUE_YANDEX_CASSA_ELECTRONIC_MONEY,
            self::VALUE_ECOIN_VOUCHER_ELECTRONIC_MONEY,
            self::VALUE_PAYBOX_KZ_CASH_BY_CODE,
            self::VALUE_WEX_ELECTRONIC_MONEY,
            self::VALUE_WEX_BITCOIN_ELECTRONIC_MONEY,
            self::VALUE_WEX_ETHEREUM_ELECTRONIC_MONEY,
            self::VALUE_WEX_BITCOIN_CASH_ELECTRONIC_MONEY,
            self::VALUE_WINPAY_MOBILE,
            self::VALUE_WINPAY_QIWI,
            self::VALUE_WINPAY_YANDEX,
            self::VALUE_FIO_SEPA,
            self::VALUE_EXMO_ETHEREUM_ELECTRONIC_MONEY,
            self::VALUE_EXMO_BITCOIN_CASH_ELECTRONIC_MONEY,
            self::VALUE_BITFINEX_BITCOIN_ELECTRONIC_MONEY,
            self::VALUE_NORDPAY_SEPA,
            self::VALUE_MAJESTIC_SEPA,
            self::VALUE_INTERKASSA_YANDEX,
            self::VALUE_BITFINEX_LITECOIN_ELECTRONIC_MONEY,
            self::VALUE_ASTROPAY_ARGENTINA_LOCAL_BANK_TRANSFER,
            self::VALUE_ASTROPAY_CHILE_LOCAL_BANK_TRANSFER,
            self::VALUE_ASTROPAY_BRAZIL_LOCAL_BANK_TRANSFER,
            self::VALUE_ASTROPAY_COLOMBIA_LOCAL_BANK_TRANSFER,
            self::VALUE_ASTROPAY_MEXICO_LOCAL_BANK_TRANSFER,
            self::VALUE_ASTROPAY_PERU_LOCAL_BANK_TRANSFER,
            self::VALUE_ASTROPAY_URUGUAY_LOCAL_BANK_TRANSFER,
            self::VALUE_ASTROPAY_CHINA_LOCAL_BANK_TRANSFER,
            self::VALUE_CREDIT_PILOT_YANDEX,
            self::VALUE_NORDPAY_SWIFT,
            self::VALUE_BITFINEX_BITCOIN_CASH_ELECTRONIC_MONEY,
            self::VALUE_BITFINEX_RIPPLE_ELECTRONIC_MONEY,
            self::VALUE_BITFINEX_ETHEREUM_ELECTRONIC_MONEY,
            self::VALUE_BITFINEX_ZCASH_ELECTRONIC_MONEY,
            self::VALUE_BITFINEX_TRON_ELECTRONIC_MONEY,
            self::VALUE_OKLINK_INDONESIA_LOCAL_BANK_TRANSFER,
            self::VALUE_OKLINK_PHILIPPINES_LOCAL_BANK_TRANSFER,
            self::VALUE_OKLINK_THAILAND_LOCAL_BANK_TRANSFER,
            self::VALUE_OKLINK_VIETNAM_LOCAL_BANK_TRANSFER,
            self::VALUE_OKLINK_AUSTRALIA_LOCAL_BANK_TRANSFER,
            self::VALUE_OKLINK_MALAYSIA_LOCAL_BANK_TRANSFER,
            self::VALUE_RBK_BANK_CARD,
            self::VALUE_RBK_BANK_CARD_CRYPTO_NETTING,
            self::VALUE_RBK_BANK_CARD_NEW,
            self::VALUE_APPEXMONEY_BANK_CARD,
            self::VALUE_YANDEX_KASSA_BANK_CARD,
            self::VALUE_NORDPAY_SWIFT_BUSINESS,
            self::VALUE_NORDPAY_SEPA_BUSINESS,
            self::VALUE_MAJESTIC_SEPA_BUSINESS,
            self::VALUE_KRAKEN_BITCOIN_ELECTRONIC_MONEY,
            self::VALUE_KRAKEN_LITECOIN_ELECTRONIC_MONEY,
            self::VALUE_KRAKEN_BITCOIN_CASH_ELECTRONIC_MONEY,
            self::VALUE_KRAKEN_RIPPLE_ELECTRONIC_MONEY,
            self::VALUE_KRAKEN_ETHEREUM_ELECTRONIC_MONEY,
            self::VALUE_KRAKEN_ZCASH_ELECTRONIC_MONEY,
            self::VALUE_BITSTAMP_BITCOIN_ELECTRONIC_MONEY,
            self::VALUE_BITSTAMP_LITECOIN_ELECTRONIC_MONEY,
            self::VALUE_BITSTAMP_BITCOIN_CASH_ELECTRONIC_MONEY,
            self::VALUE_BITSTAMP_RIPPLE_ELECTRONIC_MONEY,
            self::VALUE_BITSTAMP_ETHEREUM_ELECTRONIC_MONEY,
            self::VALUE_BITSTAMP_GIBRALTAR_BITCOIN_ELECTRONIC_MONEY,
            self::VALUE_BITSTAMP_NORDPAY_BITCOIN_ELECTRONIC_MONEY,
            self::VALUE_BITSTAMP_NORDPAY_LITECOIN_ELECTRONIC_MONEY,
            self::VALUE_BITSTAMP_NORDPAY_BITCOIN_CASH_ELECTRONIC_MONEY,
            self::VALUE_BITSTAMP_NORDPAY_RIPPLE_ELECTRONIC_MONEY,
            self::VALUE_BITSTAMP_NORDPAY_ETHEREUM_ELECTRONIC_MONEY,
            self::VALUE_BITTREX_BITCOIN_ELECTRONIC_MONEY,
            self::VALUE_BITTREX_LITECOIN_ELECTRONIC_MONEY,
            self::VALUE_BITTREX_BITCOIN_CASH_ELECTRONIC_MONEY,
            self::VALUE_BITTREX_RIPPLE_ELECTRONIC_MONEY,
            self::VALUE_BITTREX_ETHEREUM_ELECTRONIC_MONEY,
            self::VALUE_BITTREX_ZCASH_ELECTRONIC_MONEY,
            self::VALUE_BITTREX_TRON_ELECTRONIC_MONEY,
            self::VALUE_OKCOIN_BITCOIN_ELECTRONIC_MONEY,
            self::VALUE_OKCOIN_LITECOIN_ELECTRONIC_MONEY,
            self::VALUE_OKCOIN_BITCOIN_CASH_ELECTRONIC_MONEY,
            self::VALUE_OKCOIN_RIPPLE_ELECTRONIC_MONEY,
            self::VALUE_OKCOIN_ETHEREUM_ELECTRONIC_MONEY,
            self::VALUE_OKCOIN_ZCASH_ELECTRONIC_MONEY,
            self::VALUE_OKCOIN_TRON_ELECTRONIC_MONEY,
            self::VALUE_BINANCE_BITCOIN_ELECTRONIC_MONEY,
            self::VALUE_BINANCE_LITECOIN_ELECTRONIC_MONEY,
            self::VALUE_BINANCE_BITCOIN_CASH_ELECTRONIC_MONEY,
            self::VALUE_BINANCE_RIPPLE_ELECTRONIC_MONEY,
            self::VALUE_BINANCE_ETHEREUM_ELECTRONIC_MONEY,
            self::VALUE_BINANCE_ZCASH_ELECTRONIC_MONEY,
            self::VALUE_BINANCE_TRON_ELECTRONIC_MONEY,
            self::VALUE_WINPAY_BITCOIN_ELECTRONIC_MONEY,
            self::VALUE_OKLINK_UAE_LOCAL_BANK_TRANSFER,
            self::VALUE_OKLINK_CANADA_LOCAL_BANK_TRANSFER,
            self::VALUE_OKLINK_DOKU_ELECTRONIC_MONEY,
            self::VALUE_OKLINK_VIMO_ELECTRONIC_MONEY,
            self::VALUE_ROYAL_PAY_BANK_CARD,
            self::VALUE_ROYAL_PAY_ADV_PROJECT_BANK_CARD,
            self::VALUE_ROYAL_PAY_CIS_BANK_CARD,
            self::VALUE_GRATA_PAY_BANK_CARD,
            self::VALUE_GATE_EXPRESS_BANK_CARD,
            self::VALUE_PAYSOFT_BANK_CARD,
            self::VALUE_GPAY_BANK_CARD,
            self::VALUE_BITFINEX_USDTETHER_ELECTRONIC_MONEY,
            self::VALUE_BINANCE_USDTETHER_OMNI_ELECTRONIC_MONEY,
            self::VALUE_BINANCE_USDTETHER_ERC_20_ELECTRONIC_MONEY,
            self::VALUE_BINANCE_USDTETHER_TRC_20_ELECTRONIC_MONEY,
            self::VALUE_OKCOIN_USDTETHER_ELECTRONIC_MONEY,
            self::VALUE_OKCOIN_USDTETHER_ERC_20_ELECTRONIC_MONEY,
            self::VALUE_OKCOIN_USD_COIN_ELECTRONIC_MONEY,
            self::VALUE_OKCOIN_DAI_ELECTRONIC_MONEY,
            self::VALUE_OKCOIN_PAXOS_STANDARD_ELECTRONIC_MONEY,
            self::VALUE_OKCOIN_TRUE_USD_ELECTRONIC_MONEY,
            self::VALUE_OKCOIN_USDK_ELECTRONIC_MONEY,
            self::VALUE_OKCOIN_STASIS_EURO_ELECTRONIC_MONEY,
            self::VALUE_OKCOIN_USDTETHER_TRC_20_ELECTRONIC_MONEY,
            self::VALUE_EXMO_USDTETHER_ELECTRONIC_MONEY,
            self::VALUE_TALKBANK_WITHDRAWAL_TO_BANK_CARD,
            self::VALUE_TALKBANK_WITHDRAWAL_TO_BANK_CARD_NEW,
            self::VALUE_BRZTOKEN_ELECTRONIC_MONEY,
            self::VALUE_EPAY_PAYOUT_TO_BANK_ACCOUNT,
            self::VALUE_EPAY_PAYOUT_THROUGH_CASH_AGENT,
            self::VALUE_GPAY_BANK_ACCOUNT,
        );
    }
}
